S3 storage i/support remote sources
takipi/takipi-storage pull request #21
Opened 2017-02-21 16:21 UTC by shimonmagal

2017-02-26 10:09 UTC, chook requested changes

2017-02-26 10:09 UTC, chook commented on docker/Dockerfile
> -# Logs are written to <storage>/log folder and both should be persistent outside of the running container
the both here is (a) logs folder, (b) storage folder from previous line

2017-02-26 10:09 UTC, chook commented on README.md
> +With thanks to moovel for developting this version supporting s3: https://github.com/moovel/takipi-storage/tree/s3-storage
typo in developting + grammer

2017-02-26 10:09 UTC, chook commented on docker/README.md
> +- configure bucket, access key and password in settings.yml
In AWS jargon this is secret and not password

2017-02-26 10:09 UTC, chook commented on docker/settings.yml
> +# this requires the alpn-boot library on the JVM's boot classpath
it's time we remove this spdy nonesense and change it to a https 8443 commented out

2017-02-26 10:09 UTC, chook commented on src/main/java/com/takipi/oss/storage/fs/SimplePathRecord.java
> +public class SimplePathRecord  implements BaseRecord {
double space before implements

2017-02-26 10:09 UTC, chook commented on src/main/java/com/takipi/oss/storage/fs/SimplePathRecord.java
> +        {
Our OSS is the regular Java one, which means the bracket should be inlined

2017-02-26 10:09 UTC, chook commented on src/main/java/com/takipi/oss/storage/fs/Record.java
> +       return  this.getServiceId() + "/" + this.getType() + "/" + this.getKey();
perhaps we should move "/" to a constant (or use File.separator)

2017-08-01 23:01 UTC, shimonmagal commented on docker/Dockerfile
> -# Logs are written to <storage>/log folder and both should be persistent outside of the running container
Sure, but there is no actual storage folder in this case

2017-08-02 11:49 UTC, chook commented on settings.yml
> +# If using attaching IAM Role to instance leave accessKey and secretKey empty.
why are settings.yml defaulting to s3?

2017-08-02 11:49 UTC, chook commented on src/main/java/com/takipi/oss/storage/TakipiStorageMain.java
> +        if ( credentials.getAccessKey() != null && !credentials.getAccessKey().isEmpty() &&
styles

2017-08-02 15:21 UTC, chook commented on settings.yml
> +# If using attaching IAM Role to instance leave accessKey and secretKey empty.
- [x] agreed that in the base branch of this PR, the default is still S3.

2017-08-03 21:57 UTC, chook commented
my eclipse is going crazy with warnings about Filesystem the raw type. @shimonmagal what's up with that?

2017-08-08 11:37 UTC, merged